# -*- coding: utf-8 -*-
"""20 jun class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-ox3WdVWbkGHNO8p5QkGNlu0vrA2obc

# **String**
"""

p = 20
q = 20
r = 20

p = q = r = 20

print(id(p))
print(id(q))
print(id(r))

p1,q1,r1 = 20

p1,q1,r1 = 20, 25, 30

print(id(p1))
print(id(q1))
print(id(r1))

"""# **String**"""

s = "Hello Python"
s

len(s)

s[0]  # forward indexing

s[-1] # backward indexing

s[:]

s

s[11]

s[0:5]

s[6:9]

s[-5:-1]

s = "Hello Python"
s

s

s[2:]

s

s[:6]

s

s[::-1]

s[0:10:5]

s1 = 'nareshit'
s1

s1[0:10]