# -*- coding: utf-8 -*-
"""20 jun Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evbbeco8ElsKIL8ZZjmyexH9Zk7-t7eD
"""

import sys
import keyword
import operator
from datetime import datetime
import os

print(keyword.kwlist)   # List all Python keywords

len(keyword.kwlist) # Python contains 35 keywords

"""# **Identifiers**"""

1var = 10  # Identifier can't start with a digit

val2@ = 35  # Indentifier can't use special symbols

import = 125  # Keywords can't be used as identifiers

"""
Correct way of defining an identifier
(Identifiers can be a combination of letters in lowercase (a to z) or uppercase
"""

val2 = 10

val_ = 99

"""# Comments in **Python**"""

# Single line comment
val1 = 10

#Multiple
#line
#comment
val1 = 10

'''
Multiple
line
comment
'''
val1 = 10

"""
Multiple
line
comment
"""
val1 = 10

"""# **Statements**"""

p = 20  #Creates an integer object with value 20 and assigns the variable p to p
q = 20  # Create new reference q which will point to value 20. p & q will be poi

















