# -*- coding: utf-8 -*-
"""21 jun Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p3dFfdKdm7OHPzhU6toH1Qe5LXD6GjAq

# **Python type casting or type conversion**
"""

int(2.3)

int(2.3, 4.5)

int(True)

int(False)

int(True, False)

int(true)

print(int(2.3))  # float - int
print(int(True)) # bool - int
print(int('10'))  # string - int
print(int(1+2j))  #complex - int not possible

int('one')

int('1')

print(float(2))

print(float(False))

print(float(2 + 3j))

print(float('two'))

print(float('2'))

complex(10)

complex(10, 20)

complex(10,20, 30)

complex(2.3, 5.)

complex(5, 2.3)

complex(False, False)

complex('1', 23)

complex( 23,'1')

complex('1')

print(bool(1))
print(bool(1.1))
print(bool(1+2j))
print(bool('nit'))

bool(  )

str(2)

str(2.2)

str(True)

str(1+2j)



